"""Strategy specifications — declarative, reproducible research hypotheses.

A :class:`StrategySpec` is a pure, serializable description of a trading rule:
entry/exit conditions over a feature library, an optional market-regime gate,
the supported timeframes and the parameter values used to build it. Specs are
generated by :class:`StrategyGenerator`, evaluated by :class:`StrategyEvaluator`
and stored in the :class:`StrategyRegistry`. ``encode_spec``/``decode_spec``
round-trip a spec to/from JSON-safe dicts so experiments can be reproduced.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from enum import StrEnum
from typing import Any

from qtrader.domain.value_objects import Interval


class FeatureCategory(StrEnum):
    """Feature families the generator samples from (no blind combinations)."""

    TREND = "trend"
    MOMENTUM = "momentum"
    VOLUME = "volume"
    VOLATILITY = "volatility"
    EXIT = "exit"


class Operator(StrEnum):
    """Comparison operators over feature values (value or cross-feature)."""

    GT = ">"
    LT = "<"
    GE = ">="
    LE = "<="
    CROSS_ABOVE = "cross_above"
    CROSS_BELOW = "cross_below"


@dataclass(frozen=True, slots=True)
class Condition:
    """One primitive test against a feature column.

    ``ref_feature`` compares against another column instead of ``value``
    (e.g. ``ema_9 > ema_21``); cross operators need the previous bar.
    """

    feature: str
    op: Operator
    value: float = 0.0
    ref_feature: str | None = None

    def __post_init__(self) -> None:
        if self.ref_feature is not None and self.ref_feature == self.feature:
            raise ValueError("ref_feature must differ from feature")


@dataclass(frozen=True, slots=True)
class EntryRule:
    """Entry conditions (AND by default; ``any`` via ``logic``)."""

    conditions: tuple[Condition, ...] = ()
    logic: str = "all"

    def __post_init__(self) -> None:
        if self.logic not in ("all", "any"):
            raise ValueError(f"unknown entry logic {self.logic!r}")


@dataclass(frozen=True, slots=True)
class ExitRule:
    """Exit conditions (any condition closes the position by default)."""

    conditions: tuple[Condition, ...] = ()
    logic: str = "any"

    def __post_init__(self) -> None:
        if self.logic not in ("all", "any"):
            raise ValueError(f"unknown exit logic {self.logic!r}")


@dataclass(frozen=True, slots=True)
class RegimeFilter:
    """Optional market-regime gate: entries only fire while satisfied."""

    conditions: tuple[Condition, ...] = ()


@dataclass(frozen=True, slots=True)
class StrategySpec:
    """One generated strategy hypothesis (unique id + version)."""

    id: str
    name: str
    version: int = 1
    direction: str = "long"
    entry: EntryRule = field(default_factory=EntryRule)
    exit: ExitRule = field(default_factory=ExitRule)
    regime: RegimeFilter | None = None
    timeframes: tuple[Interval, ...] = (Interval.D1,)
    params: dict[str, Any] = field(default_factory=dict)
    features: tuple[str, ...] = ()
    complexity: int = 0
    description: str = ""

    def __post_init__(self) -> None:
        if not self.id:
            raise ValueError("strategy id must not be empty")
        if self.version < 1:
            raise ValueError("strategy version must be >= 1")
        if self.direction not in ("long", "short", "long_short"):
            raise ValueError(f"unsupported direction {self.direction!r}")
        if not self.timeframes:
            raise ValueError("strategy must support at least one timeframe")
        if not self.entry.conditions and not self.exit.conditions:
            raise ValueError("strategy must define at least an entry or an exit rule")


def _encode_conditions(conditions: tuple[Condition, ...]) -> list[dict[str, Any]]:
    return [asdict(c) for c in conditions]


def _decode_conditions(data: list[dict[str, Any]]) -> tuple[Condition, ...]:
    return tuple(
        Condition(
            feature=item["feature"],
            op=Operator(item["op"]),
            value=float(item.get("value", 0.0)),
            ref_feature=item.get("ref_feature"),
        )
        for item in data
    )


def encode_spec(spec: StrategySpec) -> dict[str, Any]:
    """Serialize a spec to a JSON-safe dict (for registry/export)."""
    return {
        "id": spec.id,
        "name": spec.name,
        "version": spec.version,
        "direction": spec.direction,
        "entry": {
            "conditions": _encode_conditions(spec.entry.conditions),
            "logic": spec.entry.logic,
        },
        "exit": {
            "conditions": _encode_conditions(spec.exit.conditions),
            "logic": spec.exit.logic,
        },
        "regime": (
            {"conditions": _encode_conditions(spec.regime.conditions)}
            if spec.regime is not None
            else None
        ),
        "timeframes": [iv.value for iv in spec.timeframes],
        "params": spec.params,
        "features": list(spec.features),
        "complexity": spec.complexity,
        "description": spec.description,
    }


def decode_spec(data: dict[str, Any]) -> StrategySpec:
    """Rebuild a spec from :func:`encode_spec` output."""
    return StrategySpec(
        id=str(data["id"]),
        name=str(data["name"]),
        version=int(data.get("version", 1)),
        direction=str(data.get("direction", "long")),
        entry=EntryRule(
            conditions=_decode_conditions(data["entry"]["conditions"]),
            logic=str(data["entry"].get("logic", "all")),
        ),
        exit=ExitRule(
            conditions=_decode_conditions(data["exit"]["conditions"]),
            logic=str(data["exit"].get("logic", "any")),
        ),
        regime=(
            RegimeFilter(conditions=_decode_conditions(data["regime"]["conditions"]))
            if data.get("regime") is not None
            else None
        ),
        timeframes=tuple(Interval(iv) for iv in data["timeframes"]),
        params=dict(data.get("params", {})),
        features=tuple(str(f) for f in data.get("features", ())),
        complexity=int(data.get("complexity", 0)),
        description=str(data.get("description", "")),
    )


__all__ = [
    "Condition",
    "EntryRule",
    "ExitRule",
    "FeatureCategory",
    "Operator",
    "RegimeFilter",
    "StrategySpec",
    "decode_spec",
    "encode_spec",
]
